[book]
title = "Topos Reference"
authors = ["finegeometer"]
language = "en"
multilingual = false
src = "src"

[build]
extra-watch-dirs = ["./macros.txt"]

[preprocessor.katex]
after = ["links"]
macros = "macros.txt"

[output.html]
default-theme="navy"
preferred-dark-theme="navy"
git-repository-url="https://github.com/finegeometer/topos-notes"
site-url="https://finegeometer.github.io/topos-notes/"

[output.html.fold]
enable = true
level = 1

